#Developed by _ItsAndrew_
#Main configuration file for PlaytimeUtils.

#The prefix for plugin chat messages. Leave blank for no prefix
chat-prefix: "&f&l[&e&lPUtils&f&l]"

#Configure the database manager
database:
  type: sqlite  #This is the type of the database. If you run a network with multiple servers, use 'mysql'! If you run only 1 server, use 'sqlite'!
  file-name: "database.db" #This is ONLY for SQLite, and it is ONLY the name for the file.

  #These are the settings for the MySQL database. If you don't use MySQL, you can ignore this.
  host: ""
  port: ""
  database: ""
  username: ""
  password: ""

#Configure general messages. Use '&' for colors/styles. You can also use PAPI placeholders!
messages:
  no-permission: "&cYou don't have permission to do that!"
  my-playtime: "&aYour playtime is &e&l%playtime_mainValue%&a!" #Use %playtime_mainValue% to display the main playtime
  player-playtime: "&a%player%'s playtime is &e&l%playtime_mainValue%&a!" #Use %player% to display the player's name and %playtime_mainValue% to display their main playtime'
  player-afk: "&7You are now AFK!"
  player-no-more-afk: "&7You are not AFK anymore."

  #Configure the top 3 message that can be sent when a player runs /topplaytime
  #Available Placeholders: '%playtime_top1ign%'/'%playtime_top1%' -> Top 1 player's IGN/Playtime
  #                        '%playtime_top2ign%'/'%playtime_top2%' -> Top 2 player's IGN/Playtime
  #                        '%playtime_top3ign%'/'%playtime_top3%' -> Top 3 player's IGN/Playtime
  top-3-players:
    - "&c&l---------------------------------"
    - " "
    - "                  &d&lTOP PLAYTIME"
    - " "
    - "           &e&l1. &e%playtime_top1ign%   &f%playtime_top1%"
    - "           &7&l2. &7%playtime_top2ign%   &f%playtime_top2%"
    - "           &6&l3. &6%playtime_top3ign%   &f%playtime_top3%"
    - " "
    - "&c&l---------------------------------"

#Set the seconds for when a player should be set on AFK
afk-seconds: 4 #In seconds!
lp-afk-prefix: "&7&l[AFK] &7" #Set the prefix for an AFK player. Note that this only works if you have LuckPerms enabled on your server.

#Configure the sound / titles when a player joins for the first time. Use '&' for styles/colors.
#First join means if the player is not registered in the database.
#You can also use PAPI placeholders!
first-join:
  toggle: true #If you want this feature or not
  title: "&d&lWELCOME!"
  subtitle: ""

  sound: ENTITY_PLAYER_LEVELUP
  sound-volume: 1.0
  sound-pitch: 1.0


#Configure the Reward System. This will be like a mini-tournament system.
reward-system:
  toggle: false #If you want to use Rewards or not.

  #Set the timer for the tournament. (In DAYS)
  tournament-timer: 3 #As you can see, by default it is set to 7 days/1 week.

  #Configure the tournament chat message at these timestamps. You may use PAPI placeholders and '&' for colors!
  tournament-messages:
    #You may even use the word 'discord' in any of the messages below, then put your discord server link here to have a clickable word which
    #will redirect to your Discord Server.
    discord-link:
    discord-hover-text: "Click here to join our Discord Server!"

    #Placeholders: '%tournament_enddate%' -> The date (e.g.: 24 Mar 2026) when the tournament ends.
    #              '%tournament_duration%' -> The duration of the tournament (e.g.: 5d 12h 30m 45s)
    start:
      - "&c&l======[&f&lPLAYTIME TOURNAMENT STARTS &e&lNOW&c&l]======"
      - " "
      - "&7Until &e%tournament_enddate%&7, you have the chance to win &e&limpressive rewards&7!"
      - "&7Play as much as you can, &eclimb the leaderboard&7 and &eget the best rewards&7."
      - " "
      - "&b&lHow Can I See My Playtime?"
      - "    &7To see your playtime, use the &e/myplaytime&7 command!"
      - "&7You may also use &e/topplaytime&7 to see the top 3 players!"
      - " "
      - "        &7We wish you all &6&lGood Luck &7and &e&lHappy Playing&7!"
      - "         &7&oFor more information, join our &9Discord Server&7!"
      - " "
      - "&c&l======[&f&lPLAYTIME TOURNAMENT ENDS IN &4&l%tournament_duration%&c&l]======"


    disabled:
      - "&c&l===============[&f&lPLAYTIME TOURNAMENT DISABLED&c&l]==============="
      - " "
      - "   &7The tournament &ehas been disabled &7by the server owner!"
      - "&7If you would like to know more, see more information on &9our Discord Server."
      - "&c&l===================================================================="

    end:

    #Placeholders: '%tournament_enddate%' -> The date (e.g.: 24 Mar 2026) when the tournament ends.
    #              '%tournament_duration%' -> The duration of the tournament (e.g.: 5d 12h 30m 45s)
    1/3-of-duration:
      - "&c&l======[&f&lPLAYTIME TOURNAMENT ANNOUNCEMENT&c&l]======"
      - " "
      - "&7Want to win &eexpensive items &7easily? Then this event is for you!"
      - "&7Play as much as you can, &eclimb the leaderboard&7 and &eget the best rewards&7!"
      - " "
      - "&b&lHow Can I See My Playtime?"
      - "    &7To see your playtime, use the &e/myplaytime&7 command!"
      - "&7You may also use &e/topplaytime&7 to see the top 3 players!"
      - " "
      - "       &7Have a question? Join our &9Discord Server&7!"
      - "&c&l======[&f&lPLAYTIME TOURNAMENT ENDS IN &4&l%tournament_duration%&c&l]======"

    #Placeholders: '%tournament_enddate%' -> The date (e.g.: 24 Mar 2026) when the tournament ends.
    #              '%tournament_duration%' -> The duration of the tournament (e.g.: 5d 12h 30m 45s)
    half-of-duration:
      - "&c&l======[&f&lPLAYTIME TOURNAMENT ANNOUNCEMENT&c&l]======"
      - " "
      - "&7Want to win &eexpensive items &7easily? Then this event is for you!"
      - "&7Play as much as you can, &eclimb the leaderboard&7 and &eget the best rewards&7!"
      - " "
      - "&b&lHow Can I See My Playtime?"
      - "    &7To see your playtime, use the &e/myplaytime&7 command!"
      - "&7You may also use &e/topplaytime&7 to see the top 3 players!"
      - " "
      - "       &7Have a question? Join our &9Discord Server&7!"
      - "&c&l======[&f&lPLAYTIME TOURNAMENT ENDS IN &4&l%tournament_duration%&c&l]======"

    #Placeholders: '%tournament_enddate%' -> The date (e.g.: 24 Mar 2026) when the tournament ends.
    #              '%tournament_duration%' -> The duration of the tournament (e.g.: 5d 12h 30m 45s)
    5/6-of-duration:
      - "&c&l======[&f&lPLAYTIME TOURNAMENT ANNOUNCEMENT&c&l]======"
      - " "
      - "&7Want to win &eexpensive items &7easily? Then this event is for you!"
      - "&7Play as much as you can, &eclimb the leaderboard&7 and &eget the best rewards&7!"
      - " "
      - "&b&lHow Can I See My Playtime?"
      - "    &7To see your playtime, use the &e/myplaytime&7 command!"
      - "&7You may also use &e/topplaytime&7 to see the top 3 players!"
      - " "
      - "       &7Have a question? Join our &9Discord Server&7!"
      - "&c&l======[&f&lPLAYTIME TOURNAMENT ENDS IN &4&l%tournament_duration%&c&l]======"


  #Configure the items/exp levels that will be given to players who win the tournament.
  rewards:
    first-place:
      exp-levels:
      items:

    second-place:
      exp-levels:
      items:

    third-place:
      exp-levels:
      items: