name: PlaytimeUtils
description: $description
version: '${version}'

main: me.itsandrew.playtimeUtils.PlaytimeUtils
api-version: '1.21'
load: POSTWORLD

authors: [_ItsAndrew_]

softdepend: [PlaceholderAPI]

permissions:
  playtimeutils.myplaytime:
    description: Allows the player to see their own playtime.
    default: true

  playtimeutils.playtime:
    description: Allows the player to see someone else's playtime.
    default: op


commands:
  myplaytime:
    description: See your own playtime.
    permission: playtimeutils.myplaytime

  playtime:
    description: See someone else's playtime.
    permission: playtimeutils.myplaytime
